### ISSUE TITLE
demo跑不通？

### ISSUE THREAD

**Issue by qiudongwei** [egret-labs/egret-docs#25]
按照demo去编码，添加的3d物体所在的canvas图片有一个zIndex=-1，导致预览效果一片灰色，通过开发者工具取消掉zIndex=-1这个属性，就能看见改canvas层，请问是什么原因呢？
![image](https://user-images.githubusercontent.com/26505680/32649725-bb00c6a4-c5c0-11e7-8e7f-e26b5829a48a.png)

**Comment by runinspring** [comment]
新的3D文档，请看 http://developer.egret.com/cn/docs/3d/tutorials/README.html
