### ISSUE TITLE
新建小程序的 demo,task.json 未配置,并且去配置搜不到 task.json 的配置项

### ISSUE THREAD

**Issue by Easyzhan** [egret-labs/egret-docs#28]
正在初始化运行环境, 请稍等...
运行环境初始化错误: Invalid Version: 1.02.1801081

**Comment by think55** [comment]
我的也是这样的问题

**Comment by Easyzhan** [comment]
<img width="393" alt="wx20180116-195502 2x" src="https://user-images.githubusercontent.com/8928783/34988259-1dfc1b74-faf9-11e7-9cda-070f13948175.png">

**Comment by VipMinF** [comment]
我的也是这个问题

**Comment by Easyzhan** [comment]
666 也不解决就稀里糊涂，close 了
