### ISSUE TITLE
这个也有点小急，我用了EXML.load去动态加载皮肤，发布成微信小游戏后，提示EXML is not defined

### ISSUE THREAD

**Issue by df257** [egret-labs/egret-docs#31]
不知是否有其他加载皮肤的方法？

**Comment by df257** [comment]
@yjtx @runinspring @wibrst @mebiusashan

**Comment by dily3825002** [comment]
加我微信 lovemin3825002




发自网易邮箱大师
在2018年03月27日 09:40，DFB 写道：

@yjtx@runinspring@wibrst@mebiusashan

**Comment by df257** [comment]
@dily3825002 加了
