### ISSUE TITLE
安裝不了EgretWing-v4.1.5

### ISSUE THREAD

**Issue by hou000123** [egret-labs/egret-docs#32]
![image](https://user-images.githubusercontent.com/13622473/37979829-2c7329f4-321c-11e8-8ee0-db9b90b48052.png)

系統: Win7
![image](https://user-images.githubusercontent.com/13622473/37979896-5759ff6c-321c-11e8-99ec-ee3185f139a3.png)

![image](https://user-images.githubusercontent.com/13622473/37980066-c39d9a08-321c-11e8-9f50-f4474e354dc2.png)

有没有解決辦法或替代方案?

**Comment by dily3825002** [comment]
非常抱歉，暂不支持32位系统，请使用64位系统




发自网易邮箱大师
在2018年03月28日 00:10，hou000123 写道：

系統: Win7
