### ISSUE TITLE
来自Texture文档的误导性描述错误

### ISSUE THREAD

**Issue by iClassic-Live** [egret-labs/egret-docs#36]
![error](https://user-images.githubusercontent.com/33870652/42722412-fea96fb2-877d-11e8-8daa-de17d786c35c.png)
来自Texture文档的描述错误，箭头所指应该是res而不是des，容易造成误导，出错的页面网址为：http://developer.egret.com/cn/github/egret-docs/Engine2D/bitmapTexture/useTexture/index.html

**Comment by runinspring** [comment]
感谢反馈，已经修改
