### ISSUE TITLE
描述错误

### ISSUE THREAD

**Issue by hisuu1234** [egret-labs/egret-docs#8]
事件的信息可以包括事件，地点，干什么。    事件应该是时间。

**Comment by iClassic-Live** [comment]
![error](https://user-images.githubusercontent.com/33870652/42722383-9d5cfa76-877d-11e8-9123-640562953cff.png)
来自TextureSet文档的描述错误，箭头所指应该是res而不是des，容易造成误导，出错的页面网址为：http://developer.egret.com/cn/github/egret-docs/Engine2D/bitmapTexture/useTexture/index.html
